GET http://localhost:3001/api/persons
###
GET http://localhost:3001/api/persons/6658469cf05144cd34b6f79s

###

DELETE http://localhost:3001/api/persons/6658492cd689b26c7827683c

###

POST http://localhost:3001/api/persons
Content-Type: application/json

    {
      "name": "Pedro Hellas",
      "number":"1234"
    }
